### ISSUE TITLE
Hi Team, getting this issue while trying to integrate my node api with Treblle. Need help

### ISSUE THREAD

**Issue by mitra-shan** [Treblle/treblle-node#9]
This is a simple Typescript API but, Treblle is failing to handle the request.

[error] Sending data to Treblle failed (it's possibly a network error) TypeError: function () {
      let value = container[varName]

      log(`will be read from the environment using "${accessor.name}" accessor`)

      if (typeof value === 'undefined') {
        if (typeof defValue === 'undefined' && isRequired) {
          log('was not found in the environment, but is required to be set')
          // Var is not set, nor is a default. Throw an error
          raiseError(undefined, 'is a required variable, but it was not set')
        } else if (typeof defValue !== 'undefined') {
          log(`was not found in the environment, parsing default value "${defValue}" instead`)
          value = defValue
        } else {
          log('was not found in the environment, but is not required. returning undefined')
          // return undefined since variable is not required and
          // there's no default value provided
          return undefined
        }
      }

      if (isRequired) {
        log('verifying variable value is not an empty string')
        // Need to verify that required variables aren't just whitespace
        if (value.trim().length === 0) {
          raiseError(undefined, 'is a required variable, but its value was empty')
        }
      }

      if (isBase64) {
        log('verifying variable is a valid base64 string')
        if (!value.match(base64Regex)) {
          raiseError(value, 'should be a valid base64 string if using convertFromBase64')
        }
        log('converting from base64 to utf8 string')
        value = Buffer.from(value, 'base64').toString()
      }

      const args = [value].concat(Array.prototype.slice.call(arguments))

      try {
        log(`passing value "${value}" to "${accessor.name}" accessor`)

        const result = accessor.apply(
          accessor,
          args
        )

        log(`parsed successfully, returning ${result}`)
        return result
      } catch (error) {
        raiseError(value, error.message)
      }
    } is not a legal HTTP header value

**Comment by cindreta** [comment]
Hey man thank you so much for the report! We're on it and we'll get it fixed soon. ✌🏻

**Comment by mitra-shan** [comment]
Awesome @cindreta !! 👍

**Comment by akantic** [comment]
Hey @mitra-shan, I will try to long shot this first without much context 😅 
Are you by any chance providing a wrong value for `apiKey`, more precisely, this function that you have pasted?

If that is not the case, could you please provide more context about this, in particular:
1. Which integration are you using (express, koa, strapi...)?
2. Could you provide a snippet of code where you have invoked the Treblle function (`useTreblle` for example)?
3. Request data for which this error is happening, if available.

**Comment by mitra-shan** [comment]
@akantic - I am using NodeJS and Express also the API key is correct as in my Treblle project there is another similar project with NodeJS Express in that I could see all my API calls are getting recorded. But, while I used the same code snippet like -

```
export const createServer = async (): Promise<Application> => {
  const app = express();

  // section treblle
  useTreblle(app, {
    apiKey: env.get('TREBLLE_API_KEY').asString,
    projectId: env.get('TREBLLE_PROJECT_ID').asString,
    additionalFieldsToMask: ['X-Api-Key', 'secret', 'private', 'user_ssn'],
  });

  console.log(' ----------------------- ', process.env.TREBLLE_PROJECT_ID);
```

This time it's failing at treblle however it's not blocking the code and I am able to receive the response on Postman. Also one more pointer is I am able to call the API from the `test` in Treblle and getting the response successfully without but, seeing the same error on my API console.

**Comment by akantic** [comment]
I believe you are just not invoking `asString` function. So try this instead:
``` 
  useTreblle(app, {
    apiKey: env.get('TREBLLE_API_KEY').asString(),
    projectId: env.get('TREBLLE_PROJECT_ID').asString(),
    additionalFieldsToMask: ['X-Api-Key', 'secret', 'private', 'user_ssn'],
  });
 ```

**Comment by mitra-shan** [comment]
Hello @akantic you are fantastic. You resolved my eye bug. Yes you are correct this () was not there and failing. Thanks a lot for your support.

**Comment by cindreta** [comment]
@akantic FTW 🤩 Thank you both, glad it's solved
